### ISSUE TITLE
Inconsistency in README and reversed order

### ISSUE THREAD

**Issue by gnapse** [jmeas/react-composer#27]
This is from the README [as of today](https://github.com/jmeas/react-composer/blob/02d11f844e40e09633fd2f069e1d96cd8339d410/README.md):

![image](https://user-images.githubusercontent.com/15199/35881369-57b4b8be-0b5f-11e8-8637-c888a3c3c977.png)

I may be missing something, but it looks to me thaty the example without using react-composer shows the components in the same order as they are then listed in the example that uses react-composer.

But late on in the README it is stated that the order in which you list components in the `components={[ ... ]}` prop is the reverse of how they'll be merged. It says that the last you list will be the outer one. But the screenshot above does not seem to reflect that.

**Comment by jmeas** [comment]
Thanks for the issue! The README is correct. I responded over here ( https://github.com/gnapse/render-props-compose/issues/8#issuecomment-363538427 ) with the details:

> The README accurately describes how the library currently behaves. The render order is last-to-first, which is to match the behavior of common functional utilities. However, the argument order respects the array that you pass in. This may seem weird, but until a prop like functional is added, the component is really only usable with components where the render order doesn't matter (like the new Context API).

> Either way, this doesn't matter too much, I suppose, given that the order will be changing soon.

The last sentence refers to the change described in #7 to support #19

**Comment by gnapse** [comment]
I'm sorry but I still don't get it. In the screenshot above I see that the innermost component in the un-composed example is the one that receives `{...configThree}` as props. Then that component is also the last in the array list of the example that uses the `Composer` component. So it suggest to me that the last in the array is the innermost, and the first in the array is the outermost.

But then later on in that same README you see this:

![image](https://user-images.githubusercontent.com/15199/35881793-c2d4f248-0b60-11e8-9ae3-9d996a6ef10c.png)

Here it is clearly stated that the last in the array (`<C />`) is the outermost in the nesting order, and that the first one in the array (`<A />`) is the innermost. This contradicts the example at the beginning.

**Comment by jmeas** [comment]
> So it suggest to me that the last in the array is the innermost, and the first in the array is the outermost.

The reasoning here is where the misunderstanding is, I think. The render order can be anything at all, and it doesn't _necessarily_ have to have anything to do with the order of the components that you pass in, nor the order that the arguments are received in.

Does that line of reasoning make sense to you? I think once that part makes sense, then the rest follows from it.

When it comes to the argument order in the render prop, I think nobody would argue that the order there should match the order of `components`. Which is why this lib lines those two up.

However, the rendering order isn't as clear cut in my opinion. It shouldn't just be random, because, well, that would be weird, and probably a lot of code for no reason. So the two options on the table are that it either matches what you pass in, or is the reverse order.

I understand that some developers, like you, expect the render order to match the order that is passed in, but due to the rise of functional programming in JavaScript I can also see how someone would expect the exact opposite ( see https://github.com/jmeas/react-composer/issues/7#issuecomment-362945532 )!

This is because `compose(a, b, c)` **most often** runs the functions in this order: `c -> b -> a`. And because I think of "rendering a component" as being analogous to executing a function, the render order matches up with the most common implementation of the functional `compose`.

Unfortunately, I do not think that there is a "correct" render order for a component like this. My expectation is that most developers would prefer the current behavior, which is why I implemented it this way.

But I think supporting a `functional` prop ( #19 ) is the most useful feature that could be added to this lib, and in that situation, the "same-order" rendering approach makes the API a lot simpler for consumers to use.

Does that help clear things up, @gnapse ?

**Comment by gnapse** [comment]
At this point I'm inclined to think there's something wrong with me, but I still see an inconsistency between that first example and the note about the reversed order. Perhaps the fact that in that first example all components are named the same is what makes my point a bit fussier. If you were to write that first example but using three different components, how would it be?

**Comment by jmeas** [comment]
components=A,B,C
render prop argument order=A,B,C
render order=C,B,A

**Comment by gnapse** [comment]
Exactly, and I keep seeing the problem. I'll try to be more explicit. The example shown in the README composing components is this one:

```jsx
import Composer from 'react-composer';

<Composer components={[
    <RenderPropComponent {...configOne} />,
    <RenderPropComponent {...configTwo} />,
    <RenderPropComponent {...configThree} />
  ]}>
  {([resultOne, resultTwo, resultThree]) => (
    <MyComponent results={{resultOne, resultTwo, resultThree}} />
  )}
</Composer>
```

The order in which those will be rendered is this one:

```jsx
<RenderPropComponent {...configThree}>
  {resultOne => (
    <RenderPropComponent {...configTwo}>
      {resultTwo => (
        <RenderPropComponent {...config}>
          {resultThree => (
            <MyComponent results={{resultOne, resultTwo, resultThree}} />
          )}
        </RenderPropComponent>
      )}
    </RenderPropComponent>
  )}
</RenderPropComponent>
```

The component that receives `configThree` as props is C in your notation. It's the last in the render prop arguments and in the components list, but it's the outermost.

However, in the un-composed supposedly equivalent code that the README shows, the component receiving `configThree` as props is depicted as the innermost in the nesting.

At this point I am more and more convinced that there's something wrong with me: either I'm missing something and you're right, or I am very bad at explaining myself.
